os: linux
dist: xenial
install:
    - make install
before_script:
    - make test || true
script:
    - make patch
    - make test
jobs:
  include:
    - name: Salt 2016.11.8
      env: SALTVER=2016.11.8
    - name: Salt 2016.11.10
      env: SALTVER=2016.11.10
    - name: Salt 2017.7.8
      env: SALTVER=2017.7.8
    - name: Salt 2018.3.5
      env: SALTVER=2018.3.5
    - name: Salt 2018.3.5 (python3)
      env:
        - SALTVER=2018.3.5
        - SALTREPO=py3
        - PYEXEC=python3
# official version with CVE patches included
    - name: Salt 2019.2.4
      env: SALTVER=2019.2.4
      before_script: []
      script:
        - make test
    - name: Salt 2019.2.4 (python3)
      env:
        - SALTVER=2019.2.4
        - SALTREPO=py3
        - PYEXEC=python3
      before_script: []
      script:
        - make test
    - name: Salt 3000.2
      env: SALTVER=3000.2
      before_script: []
      script:
        - make test
    - name: Salt 3000.2 (python3)
      env:
        - SALTVER=3000.2
        - SALTREPO=py3
        - PYEXEC=python3
      before_script: []
      script:
        - make test
